epfl-lara/lisa

src/main/scala/lisa/KernelHelpers.scala, src/main/scala/lisa/kernel/Printer.scala, src/main/scala/lisa/kernel/proof/SCProofChecker.scala, src/main/scala/lisa/kernel/proof/SCProofCheckerJudgement.scala, src/test/scala/lisa/kernel/ProofTests.scala, src/test/scala/lisa/proven/SimpleProverTests.scala, src/test/scala/test/ProofCheckerSuite.scala
```scala
sealed abstract class SCProofCheckerJudgement:
def isValid: Boolean
case object SCValidProof extends SCProofCheckerJudgement
case class SCInvalidProof(path: Seq[Int], message: String) extends SCProofCheckerJudgement
```
Structurally equivalent to an `Option[(Seq[Int], String)]`, but makes more sense.
The negative indices weren't aligned with the rest (this was introduced by a careless copy paste).
Added the following missing syntactic sugars:
* Pattern matching extractors for infix/unary operators
```scala
formula match
case a ==> b => ...
case a <=> b => ...
```
* Sequent from tuples and various other collections
```scala
() |- (a, b)
```
* Conversions of terms to labels
=> Proof judgement ADT, sugars and printer

src/main/scala/lisa/KernelHelpers.scala, src/main/scala/lisa/kernel/fol/EquivalenceChecker.scala, src/main/scala/lisa/kernel/fol/FormulaDefinitions.scala, src/main/scala/lisa/kernel/proof/RunningTheory.scala, src/main/scala/lisa/kernel/proof/SCProofChecker.scala, src/main/scala/lisa/kernel/proof/SequentCalculus.scala, src/main/scala/lisa/settheory/SetTheoryDefinitions.scala, src/main/scala/lisa/settheory/SetTheoryZAxioms.scala, src/main/scala/lisa/settheory/SetTheoryZFAxioms.scala, src/main/scala/proven/DSetTheory/Part1.scala, src/main/scala/proven/ElementsOfSetTheory.scala, src/main/scala/proven/tactics/Destructors.scala, src/main/scala/proven/tactics/ProofTactics.scala
- Added kernel helper functions to instantiate schematic predicate or function in a whole sequent
- Corrected equivalence checker to deal correctly with empty disjunction (permits among other to use True and False in Rewrite)
- Inconsequential change in a small helper method "bindAll" so that it doesn't sort variables
- Small qol update in the function symbol definition in the running theory so that when verifying the definition of a new symbol,
it checks the formulas with variables bound from left to right and from right to left.
- InstFunSchema and InstPredSchema weren't extending SCProofStep
- Corrected minor issues with axiom files of set theory (SetTheoryZAxioms, etc)
- New file with some development of set theory, in particular theorems regarding mapping/replacement on sets and …
=> Various corrections, new set theory development as better examples.

src/main/scala/lisa/kernel/Printer.scala, src/main/scala/lisa/kernel/fol/CommonDefinitions.scala, src/main/scala/lisa/kernel/fol/FormulaLabelDefinitions.scala, src/main/scala/lisa/kernel/fol/TermLabelDefinitions.scala, src/main/scala/lisa/kernel/proof/RunningTheory.scala, src/main/scala/lisa/settheory/SetTheoryDefinitions.scala
Highlight the separation between Function/Predicate labels and possible symbols by marking constant function and predicate labels with TheorySymbol.
=> Allow adding only constant (no schematic) symbols to a running theory

lisa-examples/src/main/scala/Example.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/CommonDefinitions.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/FormulaDefinitions.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/FormulaLabelDefinitions.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/Substitutions.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/TermDefinitions.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/TermLabelDefinitions.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/RunningTheory.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/SCProof.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/SCProofChecker.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/SequentCalculus.scala, lisa-theories/src/main/scala/lisa/settheory/SetTheoryZAxioms.scala, lisa-theories/src/main/scala/lisa/settheory/SetTheoryZFAxioms.scala, lisa-utils/src/main/scala/lisa/utils/KernelHelpers.scala, lisa-utils/src/main/scala/lisa/utils/Library.scala, lisa-utils/src/main/scala/lisa/utils/Printer.scala, lisa-utils/src/main/scala/lisa/utils/TheoriesHelpers.scala, lisa-utils/src/test/scala/lisa/kernel/FolTests.scala, lisa-utils/src/test/scala/lisa/kernel/IncorrectProofsTests.scala, lisa-utils/src/test/scala/lisa/kernel/ProofTests.scala, lisa-utils/src/test/scala/lisa/test/ProofCheckerSuite.scala, lisa-utils/src/test/scala/lisa/utils/PrinterTest.scala, src/main/scala/lisa/proven/Main.scala, src/main/scala/lisa/proven/mathematics/Mapping.scala, src/main/scala/lisa/proven/mathematics/SetTheory.scala, src/main/scala/lisa/proven/tactics/SimplePropositionalSolver.scala
Merge the concept of Variables and Schematic (term) symbols, effectively by replacing 0-ary schemas by variables. Also introduce formula variables in place of 0-ary schematic predicates.
Any work on top of current LISA release should be easily adaptable by:
- Changing all instances of Arity 0 SchematicFunctionLabel by VariableLabel
- Changing all instances of Arity 0 SchematicPredicateLabel by VariableFormulaLabel
- Changing all matching on SchematicFunctionLabel by either VariableLabel, SchematicFunctionLabel or SchematicTermLabel, according to whether the arity should be =0, >0 or >=0.
- Changing all instances of multiary SchematicPredicateLabel by SchematicNPredicateLabel
- Removing the empty parenthesis () that where used to transform an Arity 0 label to a term or formula. Variables …
=> Variables change

lisa-utils/src/test/scala/lisa/test/ProofCheckerSuite.scala
This ensures that the test will fail if an invalid proof is found when a valid one was expected.
=> In ProofCheckerSuite#checkProof, fail if the proof is not valid

.github/workflows/ci.yml
It's much more useful to know if a PR passes tests than if it's formatted properly, so in the CI, let's run tests before `scalafix --check` /  `scalafmtCheck`.
=> In CI, run tests before checking style

lisa-utils/src/main/scala/lisa/utils/KernelHelpers.scala, lisa-utils/src/test/scala/lisa/kernel/InvalidProofPathTests.scala
Also add a test suite to make sure the path to the first incorrect step is reported correctly. Add a `errorMsg` extension to invalid proof judgement with complete information.
This PR depends on [#28](https://github.com/epfl-lara/lisa/pull/28) and should be merged after.
=> Add a util to recover an incorrect proof step given a path

lisa-front/src/test/scala/lisa/front/UnificationTests.scala, src/test/scala/lisa/automation/ProofTests.scala
Main changes:
- clarifications when an assertion fails 
- splitting tests into multiple tests cases to have a better picture of passing / failing tests (+ easier debug and inspection)
=> Clarify front tests

lisa-kernel/src/main/scala/lisa/kernel/fol/FormulaDefinitions.scala, lisa-utils/src/test/scala/lisa/utils/PrinterTest.scala
Analogous to the existing requirement in FunctionTerm.
=> Require that PredicateFormula's and ConnectorFormula's args correspond to the label's arity

lisa-front/src/main/scala/lisa/front/parser/FrontResolver.scala, lisa-front/src/main/scala/lisa/front/theory/SetTheory.scala, lisa-theories/src/main/scala/lisa/settheory/SetTheoryDefinitions.scala, lisa-theories/src/main/scala/lisa/settheory/SetTheoryZAxioms.scala, src/main/scala/lisa/proven/mathematics/SetTheory.scala
Rename the unordered_pair function label to unorderedPair.
=> Change the string representation of ∈ to 'elem', of ordered pair to 'pair'

lisa-utils/src/main/scala/lisa/utils/Parser.scala, lisa-utils/src/test/scala/lisa/utils/ParserTest.scala, lisa-utils/src/test/scala/lisa/utils/PrinterTest.scala
This allows to not print a space between a quantifier and the bound variable.
=> Change the symbol that precedes a schematic predicate / function from ? to '

lisa-utils/src/main/scala/lisa/utils/tactics/SimpleDeducedSteps.scala
Added API for forall instantiation as a simple deduced step. 
Currently some code is (unfortunately in a not so pretty manner) repeated between simultaneous and single quantifier instantiation due to issues with composing deduced tactics. This may be improved in the future by having the multiple instantiations compose single ones into a `DoubleStep` based `Proof` object.
=> Easy-tactics API for Forall Instantiation

lisa-utils/src/main/scala/lisa/utils/tactics/SimpleDeducedSteps.scala
Fixed usages of `ProofStepJudgement.ValidProofStep(Seq(_))` to be without Sequences to match recent changes.
=> Type fix following ProofStepJudgement for InstantiateForall

lisa-examples/src/main/scala/Example.scala, lisa-utils/src/main/scala/lisa/utils/KernelHelpers.scala, lisa-utils/src/main/scala/lisa/utils/Library.scala, lisa-utils/src/main/scala/lisa/utils/TheoriesHelpers.scala, lisa-utils/src/main/scala/lisa/utils/tactics/BasicStepTactic.scala, lisa-utils/src/main/scala/lisa/utils/tactics/ProofStepJudgement.scala, lisa-utils/src/main/scala/lisa/utils/tactics/ProofStepLib.scala, lisa-utils/src/main/scala/lisa/utils/tactics/ProofsHelpers.scala, lisa-utils/src/main/scala/lisa/utils/tactics/SimpleDeducedSteps.scala, lisa-utils/src/main/scala/lisa/utils/tactics/WithProofs.scala, src/main/scala/lisa/automation/kernel/SimplePropositionalSolver.scala, src/main/scala/lisa/proven/mathematics/Mapping.scala, src/main/scala/lisa/proven/mathematics/SetTheory.scala, src/main/scala/lisa/proven/peano_example/Peano.scala, src/test/scala/lisa/utilities/Transformations.scala
Proofs can now be written using dedicated tactics and deduced steps. Tactics can be developed as object from which a SCProof can be recomputed. Management of premises and target bottom sequent is unified, but tactics can optionally take other arguments. Tactics can be used to construct proof using a dedicated syntax and DSL. Formally, The proof is built imperatively. This means it is possible to write code in the middle of the proof (for example to print it) and it is possible to assign proof steps. The library keep track of the proof being written from start to finish. A proof may look like:
```
THEOREM("fixedPointDoubleApplication") of "∀'x. 'P('x) ⇒ 'P('f('x)) ⊢ 'P('x) ⇒ 'P('f('f('x)))" PROOF {
assume(forall(x, P(x) ==> P(f(x))))
val base = have( (P(x) ==> P(f(x)), P(f(x)) ==> …
```
=> New tactic system

lisa-front/src/main/scala/lisa/front/proof/state/ProofEnvironmentDefinitions.scala, lisa-utils/src/main/scala/lisa/utils/KernelHelpers.scala, lisa-utils/src/main/scala/lisa/utils/Library.scala, lisa-utils/src/main/scala/lisa/utils/LisaException.scala, lisa-utils/src/main/scala/lisa/utils/Parser.scala, lisa-utils/src/main/scala/lisa/utils/ParsingUtils.scala, lisa-utils/src/main/scala/lisa/utils/Printer.scala, lisa-utils/src/main/scala/lisa/utils/ProofPrinter.scala, lisa-utils/src/main/scala/lisa/utils/SecondOrderMatcher.scala, lisa-utils/src/main/scala/lisa/utils/SynonymInfo.scala, lisa-utils/src/main/scala/lisa/utils/TheoriesHelpers.scala, lisa-utils/src/main/scala/lisa/utils/tactics/BasicStepTactic.scala, lisa-utils/src/main/scala/lisa/utils/tactics/ProofsHelpers.scala, lisa-utils/src/main/scala/lisa/utils/tactics/WithTheorems.scala, lisa-utils/src/test/scala/lisa/kernel/EquivalenceCheckerTests.scala, lisa-utils/src/test/scala/lisa/test/ProofCheckerSuite.scala, lisa-utils/src/test/scala/lisa/utils/ParserTest.scala, lisa-utils/src/test/scala/lisa/utils/PrinterTest.scala, lisa-utils/src/test/scala/lisa/utils/SCProofStepFinderTests.scala, lisa-utils/src/test/scala/lisa/utils/TestUtils.scala, src/main/scala/lisa/automation/kernel/ProofTactics.scala, src/main/scala/lisa/automation/kernel/SimplePropositionalSolver.scala, src/main/scala/lisa/automation/kernel/SimpleSimplifier.scala, src/main/scala/lisa/proven/peano_example/Peano.scala, src/test/scala/lisa/automation/ProofTests.scala, src/test/scala/lisa/proven/SimpleProverTests.scala
1. Introduce Termula type, which doesn't distinguish function application from predicate application. A string is parsed into a Termula, which then gets converted into a Formula or a Term, with the appropriate checks.
Telling apart infix function and predicate application in LL1 parser does not appear feasible: consider two inputs, (x + y) < z and (a /\ b) /\ c. The parser is parsing a formula and observes '(' as the first token. It can either mean a subformula or a subterm with an infix operator, and this conflict seems fundamental. With the introduction of Termula, '(' corresponds to a start of subtermula, and the rest of the inputs is parsed either into a connector termula or an (infix) application termula.
2. Turn the parser into a class, which takes in its constructor the information …
=> Support infix functions and predicates with user-defined priorities

lisa-utils/src/main/scala/lisa/utils/tactics/BasicStepTactic.scala, lisa-utils/src/main/scala/lisa/utils/tactics/SimpleDeducedSteps.scala
Replicating proof checking at the level of construction of `DoubleStep` based proofs. **Supersedes #93 following changes in #99.**
- [implementation] the checks for fully parametrized versions of steps replicate checks from `SCProofChecker`
- Except in the case of `SUBPROOF`, which implements its own exception-based checking.
- [implementation] where possible, unparameterized versions defer checking by calling the parametrized versions, to centralize checking for a given proof step
- [documentation] error messages have been uniformized in tone and speech patterns where spotted. I have opted for active instead of passive tones wherever applicable, `"x is not y"` instead of `"x must be y"`. Previously, both existed simultaneously. 
- [bug] problems with overload resolution (#100) by …
=> Proof checking at the level of tactics

lisa-utils/src/main/scala/lisa/utils/Parser.scala, lisa-utils/src/test/scala/lisa/utils/ParserTest.scala
Most importantly, keep track of positions when parsing and report the error, highlighting the position where it occurred. Two types of errors are reported:
* unexpected input: highlight the unexpected token and suggest expected kinds of input
* expected term, got formula: highlight the unexpected formula
Since applications are eagerly converted to function or predicate application depending on the expected type, "expected formula, got term" error is currently not detected. This can be improved in the future.
Part of #86.
=> Improve kernel parser exceptions

lisa-examples/src/main/scala/Exercise.scala, lisa-theories/src/main/scala/lisa/settheory/SetTheoryDefinitions.scala, src/main/scala/lisa/proven/mathematics/SetTheory.scala
Changed names in definitions of standard set theoretic functions and predicates, e.g. `power_set` to `powerSet` to fix an error caused by `Identifier` checking for occurrences of `_` as a separator.  Relevant references (though in some currently commented proofs) were also changed. 
Side benefit: the string versions now match the Scala versions of the definitions :partying_face: .
=> QuickFix: remove occurences of _ in set theory definitions causing identifier errors

lisa-examples/src/main/scala/Exercise.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/EquivalenceChecker.scala
The special handling for the top and bot predicate labels were missing, they are now take into account.
=> Issue with top and bot constants in EqChecker

lisa-utils/src/main/scala/lisa/utils/tactics/BasicStepTactic.scala, lisa-utils/src/main/scala/lisa/utils/tactics/SimpleDeducedSteps.scala, lisa-utils/src/test/scala/lisa/utils/BasicTacticTest.scala, lisa-utils/src/test/scala/lisa/utils/ProofTacticTestLib.scala
Adding tests for proof tactics, since it seems we currently miss some errors during changes! 
Progress:
:heavy_check_mark: Hypo, Rewrite (WIP to use EqvChecker test functions),  Cut
:heavy_check_mark: Left rules
:heavy_check_mark: Right rules
:heavy_check_mark: Structural rules
Other changes to facilitate things:
:1st_place_medal: `unwrapTactic` utility to call other tactics safely
Issues: **The new tests in this PR will fail till I fix these (eventually)**
:heavy_check_mark: `LeftExists` checking
:heavy_check_mark: OCBSL/Weakening leniency
:heavy_check_mark: `InstantiateForall` not working due to argument type mismatch -> changed it to accept a sequent and check against it
=> Tests for proof tactics

lisa-utils/src/main/scala/lisa/utils/tactics/BasicStepTactic.scala
Changed weakening saying there is a mismatch in the LHS when the issue is in the RHS.
_DEFINITELY not something I spent a while confused by trying to fix my proof with._
=> Weakening message fix

lisa-kernel/src/main/scala/lisa/kernel/proof/SCProofChecker.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/SequentCalculus.scala, lisa-utils/src/main/scala/lisa/utils/tactics/BasicStepTactic.scala, lisa-utils/src/test/scala/lisa/utils/BasicTacticTest.scala
<title />
`Rewrite` continues to use `isSameSequent` to preserve the logical consistency of the sequent. Other than that use case, `Weakening` should now strictly subsume `Rewrite`.
=> Change weakening to use OL implication

build.sbt
Upgraded Scala version to `3.2.2` for builds. For the nightly version we had been using, Metals tags are not available on Maven and so all IDE features refuse to work. This should solve all of that (please). 
Tested with internal tests as well as new theorems from #115 . 
Unfortunately does not fix our type resolution errors yet #119 , #120 . 
Compilation with a newer `3.3.0-RC2` either raises dotty errors or seems to go into an infinite loop somewhere, so _settling_ for a stable version :)
=> Upgrade scala version to 3.2.2

src/main/scala/lisa/proven/mathematics/SetTheory.scala
Working on importing chapter 2 of Jech's Set Theory.
Changes and additions:
:gear: functions are now implemented as being in the set `->(x, y)`
:heavy_plus_sign: function application (changed def!)
```scala
app(f, x) = z such that (functional(f) /\ x \in dom(f) ==> (x, z) \in f) /\ (!functional(f) \/ ! x \in dom(f) ==> (z = emptySet()))
```
:heavy_plus_sign: injective, surjective, bijective functions
:wavy_dash: [WIP] invertible functions and uniqueness
:gear: Changed partial orders to be a pair (x, r)
:heavy_plus_sign: order preserving functions and isomorphisms of partial orders
:question: Well-Orders
:question: Order-types
:question: Ordinals :exclamation: :exclamation: :exclamation: 
:question: Transfinite Recursion
:question: Ordinal Arithmetic
=> Set Theory 2: The Two Functions 

lisa-examples/src/main/scala/Example.scala, lisa-examples/src/main/scala/Exercise.scala, lisa-kernel/src/main/scala/lisa/kernel/fol/EquivalenceChecker.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/RunningTheory.scala, lisa-kernel/src/main/scala/lisa/kernel/proof/SCProofChecker.scala, lisa-utils/src/main/scala/lisa/prooflib/Library.scala, lisa-utils/src/main/scala/lisa/prooflib/ProofsHelpers.scala, lisa-utils/src/main/scala/lisa/prooflib/WithTheorems.scala, lisa-utils/src/main/scala/lisa/utils/KernelHelpers.scala, src/main/scala/lisa/automation/kernel/SimpleSimplifier.scala
Ability to do sub-specified definitions.
If you want an object with propriety P(x), you can feed a proof of unique existence of Q(x) as long as Q is OL-smaller than P (so in particular it holds if Q=P/\S).
There is an example with a non-empty set in Exercise.scala.
=> Partial def

lisa-utils/src/main/scala/lisa/prooflib/BasicStepTactic.scala, lisa-utils/src/main/scala/lisa/utils/unification/UnificationUtils.scala, src/main/scala/lisa/mathematics/FirstOrderLogic.scala
Adding one step term and formula rewrite checking
Currently integrated with `RightSubstEq` as `apply2`. Needs some more testing. Currently integrating with `LeftSubstEq` (which sounds like it could be problematic!) and modifying to work with `Iff` as well.
=> Substitution Rules Param Inference

lisa-utils/src/main/scala/lisa/prooflib/OutputManager.scala, lisa-utils/src/main/scala/lisa/prooflib/ProofsHelpers.scala
Small changes:
- `assume` now accepts an `Iterable[Formula]` instead of a single `Formula` (change coming from branch funcprog).
- Fixed the issues with our console colours, changing every instance of `BLACK` to `RESET`. 
- Added a couple spaces in the printing where they were clearly missing
=> Minor Helpers Improvements

lisa-utils/src/main/scala/lisa/prooflib/Library.scala, lisa-utils/src/main/scala/lisa/prooflib/ProofsHelpers.scala, lisa-utils/src/main/scala/lisa/prooflib/TheoriesHelpers.scala
> *"Minor" in physical representation, "major" in spirit.*
> \- person coping with writing code after a while
Was adding a single word `sorry`, but discovered a few bugs on the way:
```scala
val myCorrectTheorem = Theorem(() |- P(x)) {
sorry
showCurrentProof()
}
show
```
`sorry` simply expands to `have(thesis) by Sorry`, which is a handful to write when I'm washing my hands free of responsibility for a proof.
Fixes:
:pencil2: `sequantable` to `sequentable` because I saw it somewhere
:gear: calling `show` on theorems now checks for `sorry` usage and prints with a different colour, same as the default theorem printing
:gear: `showCurrentProof` was failing as it relied on `Theorem.repr`, which raises a `null` exception. Changed to use `prettyGoal`
=> Minor fixes and faster apologies

src/main/scala/lisa/settheory/SetTheoryZFAxioms.scala
The replacement schema has been changed to use the stronger version. This is supported by Jech's Set Theory, page 166, 
Our older version purported that there existed a set `Y` that contained these elements (but not precisely these). The stronger version is provable from the weaker one with a single application of the Comprehension schema, but is closer to Jech's version of the axioms, and is also generally the version that would be used in practice. 
Old:
```scala
forall(x, (in(x, a)) ==> existsOne(y, sPsi(a, x, y))) ==>
exists(b, forall(x, in(x, a) ==> exists(y, in(y, b) /\ sPsi(a, x, y))))
```
New:
```scala
forall(a, in(a, x) ==> existsOne(b, sPsi(x, a, b))) ==>
exists(y, forall(b, in(b, y) <=> exists(a, in(a, x) /\ sPsi(x, a, b))))
```
Our version differs from Jech in that we ask that …
=> Theory Modification: Stronger Version of Replacement Schema

lisa-kernel/src/main/scala/lisa/kernel/fol/Substitutions.scala, lisa-utils/src/test/scala/lisa/utils/BasicTacticTest.scala
Added a fix for a bug discovered recently by usage of `Tautology`. 
When a substitution is made inside a formula with a binder, the bound variable is not taken into account for further recursive generation of new identifiers. This is now fixed by tracking a set of extra taken IDs.
It was failing in the following example (minified):
Substitute with formula variable `s`, `s -> (z = y)` (trivial substitution that does nothing here, but has a free variable `y`):
```
Original:
∧(∀'y_1. ¬(∀'y. ¬('y = 'y_1)))
Expected:
∧(∀'y_1. ¬(∀'y. ¬('y = 'y_1)))
Output:
∧(∀'y_1. ¬(∀'y_1. ¬('y_1 = 'y_1)))
```
Added this test case as well.
=> Fix: proper renaming of bound substitutions

lisa-utils/src/main/scala/lisa/prooflib/ProofsHelpers.scala
Assumptions are currently not taken into account when checking that a subproof has succeeded in proving its goal at the top-level.
Example:
```scala
assume(C)
val ab = have(A |- B)
have(A |- B) subproof {
have(thesis) by Restate.from(ab)
}
```
Will raise an error saying the subproof proved `C; A |- B`, instead of the expected sequent `A |- B`. So, `C` is being propagated into the subproof as expected, but the top-level correctness check fails to take this assumption into account.
This has been fixed by adding assumptions into the sequent the subproof uses for checking.
=> Fix: take assumptions into account for subproof statements

lisa-utils/src/main/scala/lisa/prooflib/SimpleDeducedSteps.scala
<insert title />
This is particularly to fix issues when using instantiation in the presence of assumptions. This is partial progress (and one of the major issues in) #161.
=> Allow `InstantiateForall` to weaken sequents

lisa-utils/src/main/scala/lisa/utils/parsing/Printer.scala
Seems, like some typos slipped through to the main branch. This PR fixes these typos allowing to compile the project
=> Fix compilation errors in util.parsing.Printer

src/main/scala/lisa/automation/kernel/SimpleSimplifier.scala, src/main/scala/lisa/mathematics/Orderings.scala, src/main/scala/lisa/mathematics/SetTheory.scala, src/test/scala/lisa/utilities/SubstitutionTacticTest.scala
- Removed the `rightLeft` parameter of `Substitution.apply2`
- `Substitution.apply2` is now called `Substitution.withExplicitRules`
Basically, you no longer have to worry about the direction of Substitution (single step only). 
I was expecting to have to do more changes to make this work. It was not so necessary till now, but this is crucial for automated equality reasoning in the near future.
=> Substitution Reversibility

lisa-kernel/src/main/scala/lisa/kernel/proof/SCProofChecker.scala, lisa-utils/src/main/scala/lisa/prooflib/BasicStepTactic.scala
Fixes a soundness bug in the kernel in the proof checking for the Cut proof step
Consider the following instance of Cut:
```
S1: A |- B, C     S2: C, D |- E
-------------------------------- Cut: wrt C
S3: A, D |- B, E
```
where `C ~ D`, and `A !~ D` in ortholattices.
The (previous) Cut implementation would attempt the following check:
```scala
isSameSetUnderOL(
{A, D} // from the conclusion: S3.LHS
{A} union {C, D}.filterNot(_ ~ C) // from the premises:  S1.LHS U (S2.RHS / cutPivot)
)
```
However, `{C, D}.filterNot(_ ~ C) = {}`, so it is checking whether `{A, D} = {A}` under OL, but a counterpart for `D` is not found on the right. This filtering is too excessive. 
We now perform a more permissive check:
```scala
isSameSetUnderOL(
{A, D} + C // from the conclusion: S3.LHS + cutPivot
{A} …
```
=> Kernel: Cut Proof Checking Fix

src/main/scala/lisa/automation/kernel/SimpleSimplifier.scala
Failed substitutions now print the formula which could not be substituted. Minor change, but I find myself looking for what failed often.
Old
```
[info]               thenHave(fun(t1, y1) /\ fun(t2, y1)) by Substitution.apply2(false, y1 === y2)
[info]    Proof tactic Substitution used in.(Recursion.scala:463) did not succeed:
[info]    Could not rewrite RHS of premise into conclusion with given substitutions.
```
New
```
[info]               thenHave(fun(t1, y1) /\ fun(t2, y1)) by Substitution.apply2(false, y1 === y2)
[info]    Proof tactic Substitution used in.(Recursion.scala:463) did not succeed:
[info]    Could not rewrite RHS of premise into conclusion with given substitutions.
[info] Formula: functionalOver('t1, initialSegment('p, 'y1)) 
```
Not necessarily intended to be merged …
=> Better Feedback for Failed Substitutions

lisa-utils/src/main/scala/lisa/utils/parsing/Printer.scala
Filled out the case in the printer for the new `Sorry` step.
I think this was not caught as a pattern match exhaustion warning due to the following line at the end of the match:
```scala
case other => throw new Exception(s"No available method to print this proof step, consider updating Printer.scala\n$other")
```
It's a tradeoff between better error messages for printing and hiding warnings when we expect them to help.
However, it is unlikely that we have users facing kernel level printing errors, of all things, so I would suggest the removal of this line. I think it would help the maintenance of the system in the future. It would raise a failed pattern match exception with the right line and file at runtime anyway if this unlikely scenario did happen. 
Edit: The catchall is gone, …
=> Printing: Sorry SC Step

build.sbt, lisa-examples/src/main/scala/Example.scala, lisa-examples/src/main/scala/MapProofTest.scala
- Updates scallion and silex sources to working versions
- Removes old-syntax and no-indent options, they're not necessary and a bit annoying
- updates lisa-examples (which was not compiling!) to be up to date with new tactics and paths
Lisa should work ootb with these. You do have to switch to sbt though
=> Build fixes

lisa-sets/src/main/scala/lisa/automation/Tableau.scala, lisa-sets/src/test/scala/lisa/automation/TableauTest.scala
Occur check in unification in the tableau prover made it impossible to solve formulas such as 
$$
\forall x. D(x) \land \neg D(f(x))
$$
A workarround is used where variables in positive literals are renamed before unification, and maped back after.
A further issue was that when a found substitution substitutes more than one variable, an arbitrary order of substitution might not work; it is necessary to instantiate the most outer quantifier first. This is now tracked.
The PR also includes additional test cases that rely on these behaviours.
=> fix tableau incompleteness

CHANGES.md, lisa-sets/src/main/scala/lisa/automation/Substitution.scala
As title says. 
The error reporting was removed and replaced with a TODO in one of the older types PRs. I've added it back, this time with the new unification API.
=> Readd failed substitution reporting

CHANGES.md, lisa-sets/src/main/scala/lisa/Main.scala, lisa-sets/src/main/scala/lisa/automation/Apply.scala
Adds an Apply tactic that can be used to prove a statement by calling a theorem with the arguments the user wants to apply to it. Avoids the use of Tautology in those cases.
- adds the file implementing the tactic in `lisa.automation`
- adds the appropriate exports in `lisa.Main`
=> Apply tactic

lisa-utils/src/main/scala/lisa/prooflib/ProofsHelpers.scala
This change fixes compilation of project when using Scala 3.6 or later due to [change in givens prioritization](https://github.com/scala/scala3/pull/19300). The issue was found by the Scala 3 Open Community Build. 
Related change in the compiler https://github.com/scala/scala3/pull/19300
New rule stats that: 
>  Instead of requiring an argument to be most specific, we now require it to be most general while still conforming to the formal parameter.
Since Scala 3.5.0 (or under -source:3.5) compiler yields warnings: 
```scala
[warn] -- Warning: /Users/wmazur/projects/community-build3/repo/lisa-sets/src/main/scala/lisa/maths/settheory/types/adt/Untyped.scala:915:99 
[warn] 915 |          have((hIsTheHeightFunction, constructorVarsInDomain(c, term)) |- in(c.term, term)) by …
```
=> Remove redundant `given Library` leading to compilation error under Scala 3.6

CHANGES.md, build.sbt, lisa-sets/src/main/scala/lisa/automation/Apply.scala, lisa-sets/src/main/scala/lisa/automation/CommonTactics.scala, lisa-sets/src/main/scala/lisa/automation/Substitution.scala, lisa-sets/src/main/scala/lisa/maths/settheory/types/TypeSystem.scala, lisa-sets/src/main/scala/lisa/maths/settheory/types/adt/Frontend.scala, lisa-sets/src/main/scala/lisa/maths/settheory/types/adt/Helpers.scala, lisa-sets/src/main/scala/lisa/maths/settheory/types/adt/Tactics.scala, lisa-sets/src/main/scala/lisa/maths/settheory/types/adt/Untyped.scala, lisa-utils/src/main/scala/lisa/fol/Common.scala, lisa-utils/src/main/scala/lisa/fol/Lambdas.scala, lisa-utils/src/main/scala/lisa/fol/Sequents.scala, lisa-utils/src/main/scala/lisa/prooflib/BasicStepTactic.scala, lisa-utils/src/main/scala/lisa/prooflib/ProofsHelpers.scala, lisa-utils/src/main/scala/lisa/prooflib/WithTheorems.scala, lisa-utils/src/main/scala/lisa/utils/parsing/Parser.scala, lisa-utils/src/main/scala/lisa/utils/parsing/ParsingUtils.scala
- Resealed the `Proof` trait following the fix of the compiler bug causing #190
- This required upgrading to Scala  >= 3.4.1
- Upgraded to 3.4.2
- There were a few minor syntax changes that had to be propagated due to deprecations, most of this was done automatically with `-rewrite -source 3.4-migration`
- SBT build cross versions are now set dynamically instead of as static strings.
=> Reseal `Proof` trait, upgrade to Scala 3.4.2

.github/workflows/ci.yml, CHANGES.md, build.sbt, project/build.properties
Complete changelist:
- Bump version to 0.7.
- Update sbt to 1.10.1.
- Move `scallion` and `silex` to depend on jars via GitHub releases instead of cloning and compiling locally.
- Tests now fork the jvm and use jvm options correctly, which also removes the relevant warning during testing.
Edit: also updated CI actions to recent versions
=> Depend on Scallion and Silex via release JARs
